### ISSUE TITLE
whdd segfaults on read test

### ISSUE THREAD

**Issue by Xord32** [whdd/whdd#1]
I have segfaults when i try to read test.
Steps to reproduce:
1. choose any device (on my comp ST3250318AS or WD10EZEX);
2. choose read test;
3. enter "posix" or "ata" to operation API field;
4. leave "start_lba" default, just press enter.
Result: segmentation fault.

OS version: Archlinux 4.3.3-2-ARCH x86-64
Hard drives: WD10EZEX as sda, ST3250318AS as sdb. All drives works good and whdd read SMART correctly.
Coredump attached.

[core.whdd.zip](https://github.com/whdd/whdd/files/90851/core.whdd.zip)

**Comment by andrey-utkin** [comment]
Core file is not helpful without your whdd binary file and probably libs.
Could you please share what gdb shows on  that core? "thread apply bt full", etc.
What is your distribution, and which version (or git revision) do you run?

**Comment by Xord32** [comment]
Trouble appears with current version from github.com/whdd/whdd and with 2.2-1 from AUR.

BUT!!! whdd works fine in gdb! For confirmation, i record it (https://drive.google.com/file/d/0B-bTizWbT0kxemtnd2cxeENiNWs/view?usp=sharing), sources gotten from github.com/whdd/whdd. 

P.S. Уместно ли здесь писать на русском?

**Comment by andrey-utkin** [comment]
Weird.
Please try to launch it under Valgrind memcheck.
Also please try to examine the core dump with gdb retrospectively, using the same commands "thread apply bt full", etc. You can obtain more meaningful stack traces if you change CFLAGS to have ```-O0```.

> P.S. Уместно ли здесь писать на русском?
Нет. Но если очень трудно на английском, то можно на русском.

**Comment by Xord32** [comment]
Under Valgrind whdd also works  [valgrind.txt](https://github.com/whdd/whdd/files/93353/valgrind.txt).
I had tried to examine core dump [gdb.txt](https://github.com/whdd/whdd/files/93404/gdb.txt).
How to change CFLAGS and fix "No symbol table info available" in gdb?

**Comment by andrey-utkin** [comment]
```make CFLAGS=-O0```

Or edit Makefile, 3rd line.

**Comment by Xord32** [comment]
[gdb_new.txt](https://github.com/whdd/whdd/files/93594/gdb_new.txt)
[whdd_bin_and_coredump.zip](https://github.com/whdd/whdd/files/93591/whdd_bin_and_coredump.zip)

I hope I did it right.

**Comment by andrey-utkin** [comment]
Thanks.
I need to review the code to figure out what is this thread without stack details.
Will have time for that next weekend I hope. Sorry for delay.

**Comment by andrey-utkin** [comment]
Sorry for delays!
Should be fixed as of 03361aa8745f6d6913b7c4e784e0300165280011.
Tricky bug, I didn't know that nested functions are allocated on stack. Thanks to warning given by gcc 5.3.0.

**Comment by Xord32** [comment]
Works fine. Thanks!
