### ISSUE TITLE
no matching function for call to ‘NCursesUserPanel<T>::get_user() const’ (a lot of problems with ncurses)

### ISSUE THREAD

**Issue by el-cpu** [whdd/whdd#18]
Hello.

Problem with ncurses both with build.sh and with build_static.sh. First there was error:

In file included from ./curses.priv.h:325:0,
                 from ../ncurses/lib_gen.c:19:
_24273.c:843:15: error: expected ‘)’ before ‘int’

After I installed tmux and followed advise here https://stackoverflow.com/questions/37475222/ncurses-6-0-compilation-error-error-expected-before-int (export CPPFLAGS="-P") it went away, but the following error appeared - again with ncurses.

OS based on Ubuntu 18.04
$ uname -r
5.7.6-gnu
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Error message (excerpt of output from terminal):

../c++/cursesp.h:89:32: note: in expansion of macro ‘THROWS’
   void OnError (int err) const THROWS(NCursesPanelException)
                                ^~~~~~
In file included from ../c++/cursesf.h:39:0,
                 from ../c++/cursesf.cc:35:
../c++/cursesp.h: In member function ‘T* NCursesUserPanel<T>::UserData() const’:
../c++/cursesp.h:256:43: error: no matching function for call to ‘NCursesUserPanel<T>::get_user() const’
     return reinterpret_cast<T*>(get_user ());
                                           ^
../c++/cursesp.h:80:9: note: candidate: void* NCursesPanel::get_user() <near match>
   void *get_user()
         ^~~~~~~~
../c++/cursesp.h:80:9: note:   passing ‘const NCursesUserPanel<T>*’ as ‘this’ argument discards qualifiers
In file included from ../c++/cursesw.h:36:0,
                 from ../c++/cursesp.h:39,
                 from ../c++/cursesf.h:39,
                 from ../c++/cursesf.cc:35:
../c++/cursesf.h: At global scope:
../c++/etip.h:374:20: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 #define THROWS(s)  throw(s)
                    ^
../c++/cursesf.h:64:38: note: in expansion of macro ‘THROWS’
   inline void OnError(int err) const THROWS(NCursesFormException) {
                                      ^~~~~~
../c++/etip.h:374:20: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 #define THROWS(s)  throw(s)
                    ^
../c++/cursesf.h:112:39: note: in expansion of macro ‘THROWS’
   inline void OnError (int err) const THROWS(NCursesFormException) {
                                       ^~~~~~
../c++/etip.h:374:20: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 #define THROWS(s)  throw(s)
                    ^
../c++/cursesf.h:394:39: note: in expansion of macro ‘THROWS’
   inline void OnError (int err) const THROWS(NCursesFormException) {
                                       ^~~~~~
In file included from ../c++/cursesf.cc:35:0:
../c++/cursesf.h: In member function ‘T* NCursesUserForm<T>::UserData() const’:
../c++/cursesf.h:707:43: error: no matching function for call to ‘NCursesUserForm<T>::get_user() const’
     return reinterpret_cast<T*>(get_user ());

../c++/cursesf.h:384:16: note: candidate: void* NCursesForm::get_user() <near match>
   inline void *get_user() {
                ^~~~~~~~
../c++/cursesf.h:384:16: note:   passing ‘const NCursesUserForm<T>*’ as ‘this’ argument discards qualifiers
In file included from ../c++/cursesw.h:36:0,
                 from ../c++/cursesp.h:39,
                 from ../c++/cursesf.h:39,
                 from ../c++/cursesf.cc:35:
../c++/cursslk.h: At global scope:
../c++/etip.h:374:20: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
 #define THROWS(s)  throw(s)
                    ^
../c++/cursslk.h:120:45: note: in expansion of macro ‘THROWS’
   inline void Error (const char* msg) const THROWS(NCursesException) {
                                             ^~~~~~
Makefile:335: recipe for target '../obj_s/cursesf.o' failed
make[4]: *** [../obj_s/cursesf.o] Error 1
Makefile:109: recipe for target 'all' failed
make[3]: *** [all] Error 2
external/ncurses/CMakeFiles/ncurses.dir/build.make:113: recipe for target 'external/ncurses/ncurses-prefix/src/ncurses-stamp/ncurses-build' failed
make[2]: *** [external/ncurses/ncurses-prefix/src/ncurses-stamp/ncurses-build] Error 2
CMakeFiles/Makefile2:217: recipe for target 'external/ncurses/CMakeFiles/ncurses.dir/all' failed
make[1]: *** [external/ncurses/CMakeFiles/ncurses.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by andrey-utkin** [comment]
Please retry.
Should fixed by cb2cd195f7317cf738209a666f8665bb2113a1ea.
