### ISSUE TITLE
How compile under Slackware 14.2?

### ISSUE THREAD

**Issue by inukaze** [whdd/whdd#19]
HI there, i can't compile under Slackware 14.2 (32 Bits neither 64 Bits)
Ever shows me the follow error message : 

```
-- Could NOT find dialog (missing: DIALOG_LIBRARY DIALOG_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:110 (message):
  Dialog library not found
```

Dialog came with the distro, you can check -> https://slackware.pkgs.org/14.2/slackware-x86_64/dialog-1.2_20130523-x86_64-1.txz.html

**Comment by andrey-utkin** [comment]
Sorry for that.
This report probably doesn't matter today.
Please report back if still an issue.
