### ISSUE TITLE
Hard Coded 512 byte sectors

### ISSUE THREAD

**Issue by SimonZerafa** [whdd/whdd#2]
Hi

This may already be on your list of issues to work on but the code assumes that all drives and devices have 512 byte sectors.

I am sure you are aware this is not the case and for working on 4K or 4K/512e drives it would be really useful to work with the correct 4K sector size.

Working with 4K sectors will speed up copying and working with bad blocks more efficiently.

Kind Regards

Simon

**Comment by andrey-utkin** [comment]
Hi!
Thanks for reporting.
WHDD actually works on a basis of block size 256*512=131072 bytes (128 KBytes) which is integer multiple of sectors, both for 512b and 4096b sectors. So this is not an actual issue.
Please correct me if I am missing something.
