### ISSUE TITLE
Can't build on Debian 10

### ISSUE THREAD

**Issue by TitaniumHocker** [whdd/whdd#20]
**Wazzup!**
Thank you for this awesome tool.

When I was trying to build on Debian 10 GNU/Linux I had an error with `pkg-config` dependency.

I opened this issue only to notify you about this error.

**Comment by diggit** [comment]
Well, this is not exactly helpful report. Can you post that error? (don't paraphrase, copy it)

**Comment by Sagrer** [comment]
Had the same problem. Seems that Debian's dialog package has no package file for pkg-config.
Solved this locally by adding file with this contents (used menuw.pc as example):

`prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib/x86_64-linux-gnu
includedir=${prefix}/include
abi_version=1
major_version=3
version=1.3.20190211-1

Name: dialog
Description: dialog library
Version: ${version}
URL: https://example.com
Libs:  -L${libdir} -ldialog
Libs.private:
Cflags:  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600
`
It works for me, but i'm not sure how this files must be created correctly (seems that it must be done while building dialog library by some tool). Also i don't know what Cflags must be for libdialog, so i just used flags from menuw, but perhaps this line may be must be empty.

So, seems that this is debian's package bug and must be fixed there?

**Comment by andrey-utkin** [comment]
Fixed by 5a8a5478ac7d88ef3c05d6ed5293f60da77a83aa
