### ISSUE TITLE
 ./build_static.sh on Linux Mint: compilation error

### ISSUE THREAD

**Issue by MaximLeyenson** [whdd/whdd#23]
`$ sudo ./build_static.sh`

> a - ../obj_g/keybound.o
 a - ../obj_g/keyok.o
a - ../obj_g/version.o
In file included from ../ncurses/curses.priv.h:283,
                 from ../ncurses/lib_gen.c:19:
_79506.c:1364:15: error: expected ‘)’ before ‘int’
../include/curses.h:1906:56: note: in definition of macro ‘mouse_trafo’
 1906 | #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
      |                                                        ^
make[4]: *** [Makefile:2011: ../obj_s/lib_gen.o] Error 1
make[3]: *** [Makefile:111: all] Error 2
make[2]: *** [external/ncurses/CMakeFiles/ncurses.dir/build.make:115: external/ncurses/ncurses-prefix/src/ncurses-stamp/ncurses-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:200: external/ncurses/CMakeFiles/ncurses.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

System:

`$ uname -a`

> Linux ladybug 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`$ cat /etc/issue`
> Linux Mint 20.1 Ulyssa

**Comment by KarelWintersky** [comment]
Same on debian 11:
```
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-26-amd64
```

**Comment by andrey-utkin** [comment]
Please retry.
Should fixed by https://github.com/whdd/whdd/commit/cb2cd195f7317cf738209a666f8665bb2113a1ea.
