### ISSUE TITLE
Domain whdd.org is expired

### ISSUE THREAD

**Issue by PNMarano** [whdd/whdd#24]
Visiting whdd.org shows that the domain is expired. (whois suggests this happened in early Sept.) Actual message below. Looks like you're still in the grace renewal window to be able to renew it if you wish. Otherwise I'd suggest removing any links to it from the readme and/or any other source files that reference it.

This domain is expired. If you're the owner, you can renew it. If you're not the owner, search for your next domain and then build your website for free on Dynadot.com!  Expired Domain Auctions

**Comment by jospezial** [comment]
At that domain you find a radio show now.
And outdated page https://whdd.github.io/

**Comment by andrey-utkin** [comment]
This is true, sorry guys.
Radio station is not too bad.
https://whdd.github.io/ I might update someday.

**Comment by jospezial** [comment]
You should better keep this open to not forget to remove the wrong domain.

**Comment by andrey-utkin** [comment]
Thanks. README updated on master.
