### ISSUE TITLE
Change ata/posix dialog to radio buttons

### ISSUE THREAD

**Issue by jospezial** [whdd/whdd#35]
The read test would be easier  to use if man has not to write the word posix into an input field.
Instead change this to radio buttons with default on ata.

**Comment by andrey-utkin** [comment]
Hi @jospezial , nice feature request. Could you please build master branch and test how it works?

**Comment by jospezial** [comment]
[build.log](https://github.com/user-attachments/files/17081038/build.log)

**Comment by jospezial** [comment]
What is your version of dialog for what you wrote https://github.com/whdd/whdd/commit/47dbfe958b1fe859fdc0a5e71352d7c6c5b5173f?
Compilation fails with dialog-1.3.20231002 to dialog-1.3.20240619, have not tested other versions.

**Comment by andrey-utkin** [comment]
Oops. I tested it with system-provided version on Fedora 39, but what matters is that what for me is a compiler warning, for you is a compiler error. I will rectify that by pinching my nose and adding an explicit type cast from `const char**` to `char**`.

**Comment by andrey-utkin** [comment]
Fix pushed.

@jospezial is your overlay public? Could you please share a link?

**Comment by jospezial** [comment]
My overlay is only local on my harddisk.
I use  a copy of https://github.com/gentoo/gentoo/tree/master/sys-block/whdd and copied [whdd-3.1.ebuild](https://github.com/gentoo/gentoo/blob/master/sys-block/whdd/whdd-3.1.ebuild) to whdd-9999.ebuild without changes.
