### ISSUE TITLE
whdd progress output broken  when window is resized, overwrites whole screen

### ISSUE THREAD

**Issue by jospezial** [whdd/whdd#36]
Whdd outout breaks when the terminal window is resized or or the screen is powerswitched of and on.
![whdd_screen_fill](https://github.com/user-attachments/assets/c35ead46-65cc-4b73-87fb-c0022725a25e)

**Comment by andrey-utkin** [comment]
True. It's low priority for me as in principle it's possible to work around once you're aware of it.

Improving this doesn't require anything particularly clever or specialised, but is a substantial effort to rework across all kinds of visualization.
I can't put it on my personal schedule for now unfortunately.
If somebody who benefits from this software professionally steps up to sponsor development of this enhancement, that would make it possible and would be great overall.
Patches are welcome, too.

**Comment by jospezial** [comment]
duplicate of #25
