### ISSUE TITLE
Unable to compile on Fedora 24 x86_64

### ISSUE THREAD

**Issue by louisvd** [whdd/whdd#7]
I hope you can advise me!  On Fedora 24 64-bit, when trying to run build.sh (and also build_static.sh) the make fails.

At the step:
[ 16%] Performing build step for 'ncurses'
*\* edit: HAVE_TCGETATTR 1
*\* edit: HAVE_TERMIOS_H 1
*\* edit: HAVE_TERMIO_H 1
*\* edit: BROKEN_LINKER 0
linking ../lib/libtinfow.so.5.9
/bin/ld: total time in link: 0.021126
/bin/ld: data size 5156864
a - ../objects/access.o
a - ../objects/add_tries.o
........ many more objects skipped for legibility ........
a - ../obj_g/version.o
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_28592.c:1364:15: error: expected ‘)’ before ‘int’
../include/curses.h:1906:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:2011: recipe for target '../obj_s/lib_gen.o' failed
make[4]: **\* [../obj_s/lib_gen.o] Error 1
Makefile:109: recipe for target 'all' failed
make[3]: **\* [all] Error 2
external/ncurses/CMakeFiles/ncurses.dir/build.make:113: recipe for target 'external/ncurses/ncurses-prefix/src/ncurses-stamp/ncurses-build' failed
make[2]: **\* [external/ncurses/ncurses-prefix/src/ncurses-stamp/ncurses-build] Error 2
CMakeFiles/Makefile2:217: recipe for target 'external/ncurses/CMakeFiles/ncurses.dir/all' failed
make[1]: **\* [external/ncurses/CMakeFiles/ncurses.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by andrey-utkin** [comment]
@louisvd , sorry for huge delay, could you please retry with up-to-date system and whdd git checkout?

**Comment by louisvd** [comment]
Hi

No worries about the long delay ... thank you for getting back to me,
though.

I have completely updated my Fedora 24 x86_64 and cloned a fresh copy
from GIT.  Upon running the build.sh I got the following errors -- I
suspect missing dependencies, but the ones referred to seem "Ubuntu-
ish" to me, not "Fedora-ish".  I even tried running it as "root".

[root@fedora whdd]# ./build.shwhich: no apt-get in (/usr/lib64/qt-
3.3/bin:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr
/bin:/root/bin)Can't find apt-get. Probably you need to install 'dialog
libncursesw5 libncursesw5-dev' packages manually.Package ncursesw was
not found in the pkg-config search path.Perhaps you should add the
directory containing `ncursesw.pc'to the PKG_CONFIG_PATH environment
variableNo package 'ncursesw' foundPackage menuw was not found in the
pkg-config search path.Perhaps you should add the directory containing
`menuw.pc'to the PKG_CONFIG_PATH environment variableNo package 'menuw'
foundPackage dialog was not found in the pkg-config search path.Perhaps
you should add the directory containing `dialog.pc'to the
PKG_CONFIG_PATH environment variableNo package 'dialog' foundPackage
ncursesw was not found in the pkg-config search path.Perhaps you should
add the directory containing `ncursesw.pc'to the PKG_CONFIG_PATH
environment variableNo package 'ncursesw' foundPackage menuw was not
found in the pkg-config search path.Perhaps you should add the
directory containing `menuw.pc'to the PKG_CONFIG_PATH environment
variableNo package 'menuw' found./version.sh . version.hcc  -std=gnu99
-pthread -D_GNU_SOURCE -I./ -I./cui/ -I./libdevcheck/
-I/usr/include/dialog    -pthread -o whdd ui_mutual.c
cui/sliding_window_renderer.c cui/ncurses_convenience.c cui/main.c
cui/vis.c cui/whole_space_renderer.c libdevcheck/posix_write_zeros.c
libdevcheck/log.c libdevcheck/procedure.c libdevcheck/ata.c
libdevcheck/smart_show.c libdevcheck/hpa_set.c libdevcheck/copy.c
libdevcheck/read_test.c libdevcheck/libdevcheck.c libdevcheck/scsi.c
libdevcheck/copy_read_strategies.c libdevcheck/render.c
libdevcheck/utils.c  -ldialog  -lm
-lrtcui/sliding_window_renderer.c:3:20: fatal error: curses.h: No such
file or directory #include <curses.h>                    ^compilation
terminated.In file included from
cui/ncurses_convenience.c:2:0:cui/ncurses_convenience.h:4:18: fatal
error: menu.h: No such file or directory #include
<menu.h>                  ^compilation terminated.cui/main.c:10:20:
fatal error: curses.h: No such file or directory #include
<curses.h>                    ^compilation terminated.In file included
from cui/vis.c:2:0:cui/vis.h:6:20: fatal error: curses.h: No such file
or directory #include <curses.h>                    ^compilation
terminated.cui/whole_space_renderer.c:3:20: fatal error: curses.h: No
such file or directory #include
<curses.h>                    ^compilation terminated.Makefile:10:
recipe for target 'whdd' failedmake: *** [whdd] Error 1



So I ran:   dnf install ncurses-devel.x86_64    which installed:
ncurses-c++-libs-6.0-6.20160709.fc24.x86_64
ncurses-devel-6.0-6.20160709.fc24.x86_64


Running ./build.sh again, I then got the following - looking better:

[louis@fedora whdd]$ ./build.shwhich: no apt-get in (/usr/lib64/qt-
3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/
sbin:/home/louis/.local/bin:/home/louis/bin)Can't find apt-get.
Probably you need to install 'dialog libncursesw5 libncursesw5-dev'
packages manually.Package dialog was not found in the pkg-config search
path.Perhaps you should add the directory containing `dialog.pc'to the
PKG_CONFIG_PATH environment variableNo package 'dialog'
found./version.sh . version.hcc  -std=gnu99 -pthread -D_GNU_SOURCE -I./
-I./cui/ -I./libdevcheck/ -I/usr/include/dialog  -D_GNU_SOURCE  -
pthread -o whdd ui_mutual.c cui/sliding_window_renderer.c
cui/ncurses_convenience.c cui/main.c cui/vis.c
cui/whole_space_renderer.c libdevcheck/posix_write_zeros.c
libdevcheck/log.c libdevcheck/procedure.c libdevcheck/ata.c
libdevcheck/smart_show.c libdevcheck/hpa_set.c libdevcheck/copy.c
libdevcheck/read_test.c libdevcheck/libdevcheck.c libdevcheck/scsi.c
libdevcheck/copy_read_strategies.c libdevcheck/render.c
libdevcheck/utils.c  -ldialog -lncursesw -ltinfo -lmenuw -lm
-lrtcui/sliding_window_renderer.c:4:20: fatal error: dialog.h: No such
file or directory #include <dialog.h>                    ^compilation
terminated.cui/main.c:11:20: fatal error: dialog.h: No such file or
directory #include <dialog.h>                    ^compilation
terminated.cui/whole_space_renderer.c:4:20: fatal error: dialog.h: No
such file or directory #include
<dialog.h>                    ^compilation terminated.Makefile:10:
recipe for target 'whdd' failedmake: *** [whdd] Error 1

Next, I ran:   dnf install dialog-devel.x86_64    which installed:
dialog-devel-1.3-4.20160424.fc24.x86_64.rpm

Running ./build.sh again I got a successful compilation.  When running
sudo make install, the process installed the whdd file, but still
complained about the dialog package, although it is installed:
# rpm -q dialog
dialog-1.3-4.20160424.fc24.x86_64

Perhaps I should have dug deeper last time!!  Nevertheless, thanks for
the useful tool.

Regards
Louis


-----Original Message-----

**Comment by diggit** [comment]
@louisvd whdd is looking for ncurses version 5. Try installing `ncurses-compat-libs-6.0`

**Comment by louisvd** [comment]
I already have that installed - see below.  But it seems that it runs,
even though it gave the error during make install.

# rpm -qa | grep -E "ncurses|dialog"dialog-1.3-
4.20160424.fc24.x86_64ncurses-libs-6.0-6.20160709.fc24.i686ncurses-
devel-6.0-6.20160709.fc24.x86_64dialog-devel-1.3-
4.20160424.fc24.x86_64ncurses-base-6.0-6.20160709.fc24.noarchkdialog-
16.08.3-1.fc24.x86_64ncurses-compat-libs-6.0-
6.20160709.fc24.x86_64ncurses-6.0-6.20160709.fc24.x86_64ncurses-libs-
6.0-6.20160709.fc24.x86_64ncurses-c++-libs-6.0-6.20160709.fc24.x86_64
Regards
Louis

-----Original Message-----

**Comment by andrey-utkin** [comment]
@diggit whdd Makefile doesn't care of version of ncurses, version 5 is mentioned in a hint of debian/ubuntu package names (which i find weird for inclusion of number but not only because of that).

As I see build fails because dialog.h is not found. @louisvd please show the listing of files installed by package `dialog-devel`, and try to add ` -I/usr/include/whatever-has-dialog.h-file ` to `CFLAGS` value in `Makefile`

**Comment by diggit** [comment]
@andrey-utkin oh, ok. I got confused by error when whdd tried to install nvurses5. Some software is strictly dependent on ncurses5. Great, that whdd is not such case.

**Comment by louisvd** [comment]
Hi

$ rpm -ql dialog-devel/usr/bin/dialog-
config/usr/include/dialog/usr/include/dialog/dialog.h/usr/include/dialo
g/dlg_colors.h/usr/include/dialog/dlg_config.h/usr/include/dialog/dlg_k
eys.h/usr/lib64/libdialog.so/usr/share/man/man3/dialog.3.gz
And out of interest:
$ rpm -qa | grep dialog | sortdialog-1.3-4.20160424.fc24.x86_64dialog-
devel-1.3-4.20160424.fc24.x86_64kdialog-16.08.3-1.fc24.x86_64

CFLAGS in the Makefile already has:    -I/usr/include/dialog

Weird one, hey?

To be clearer, here is the exact error, although it doesn't seem to
bother the process:

[louis@fedora whdd]$ sudo make install[sudo] password for
louis: Package dialog was not found in the pkg-config search
path.Perhaps you should add the directory containing `dialog.pc'to the
PKG_CONFIG_PATH environment variableNo package 'dialog'
found./version.sh . version.hinstall -D whdd /usr/local/bin/whdd[louis@
fedora whdd]$ 
Regards
Louis

-----Original Message-----

**Comment by andrey-utkin** [comment]
@louisvd So do you get your whdd binary compiled or not? If you obtained it, please close this ticket as apparently your issue is resolved now.

**Comment by louisvd** [comment]
Yes, thank you, it has compiled, just with the diag error in the message above.  I will close the ticket.  Thanks for the input.
